import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  whiteBackground: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  uploadContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  uploadCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  uploadTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#333333',
    textAlign: 'center',
    marginBottom: 8,
  },
  uploadSubtitle: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
    marginBottom: 32,
  },
  uploadButton: {
    borderRadius: 15,
    overflow: 'hidden',
    marginBottom: 16,
  },
  buttonGradient: {
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 15,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  formatInfo: {
    marginTop: 24,
    padding: 16,
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  formatTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 8,
  },
  formatText: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 4,
  },
  startContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  startCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  startTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: '#333333',
    textAlign: 'center',
    marginBottom: 24,
  },
  startInfo: {
    fontSize: 18,
    color: '#666666',
    textAlign: 'center',
    marginBottom: 12,
  },
  startButton: {
    borderRadius: 15,
    overflow: 'hidden',
    marginTop: 24,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    backgroundColor: '#ffffff',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timerText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ff6b6b',
  },
  questionCounter: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
  },
  questionNav: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#ffffff',
  },
  navButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  navButtonActive: {
    backgroundColor: '#4834d4',
    borderColor: '#4834d4',
  },
  navButtonAnswered: {
    backgroundColor: '#00d2ff',
    borderColor: '#00d2ff',
  },
  navButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
  },
  navButtonTextActive: {
    color: '#ffffff',
  },
  questionContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 8,
    backgroundColor: '#ffffff',
  },
  questionCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  questionHeader: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  subjectTag: {
    backgroundColor: '#4834d4',
    color: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    fontSize: 12,
    fontWeight: '600',
    marginRight: 8,
  },
  topicTag: {
    backgroundColor: '#f0f0f0',
    color: '#333333',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    fontSize: 12,
    fontWeight: '600',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  questionText: {
    fontSize: 16,
    color: '#333333',
    lineHeight: 24,
    marginBottom: 20,
    fontWeight: '500',
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#e0e0e0',
  },
  optionSelected: {
    backgroundColor: 'rgba(72, 52, 212, 0.1)',
    borderColor: '#4834d4',
  },
  optionCorrect: {
    backgroundColor: 'rgba(46, 213, 115, 0.1)',
    borderColor: '#2ed573',
  },
  optionWrong: {
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
    borderColor: '#ff6b6b',
  },
  optionLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333333',
    marginRight: 12,
    minWidth: 20,
  },
  optionText: {
    fontSize: 16,
    color: '#333333',
    flex: 1,
  },
  optionTextSelected: {
    color: '#333333',
    fontWeight: '600',
  },
  footer: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    backgroundColor: '#ffffff',
  },
  footerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  navFooterButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#f0f0f0',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  navButtonDisabled: {
    opacity: 0.5,
  },
  navFooterButtonText: {
    color: '#333333',
    fontSize: 16,
    fontWeight: '600',
  },
  submitButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: '#ff6b6b',
    borderRadius: 12,
  },
  submitButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  analysisContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  analysisCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  analysisTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#333333',
    textAlign: 'center',
    marginBottom: 24,
  },
  scoreCard: {
    alignItems: 'center',
    marginBottom: 24,
    padding: 20,
    backgroundColor: '#f8f9fa',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  scoreText: {
    fontSize: 24,
    fontWeight: '700',
    color: '#333333',
    marginBottom: 8,
  },
  percentageText: {
    fontSize: 36,
    fontWeight: '800',
    color: '#4834d4',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 24,
  },
  statItem: {
    alignItems: 'center',
  },
  statValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#333333',
  },
  statLabel: {
    fontSize: 14,
    color: '#666666',
    marginTop: 4,
  },
  subjectTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#333333',
    marginBottom: 16,
  },
  subjectRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#f8f9fa',
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  subjectName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
  },
  subjectScore: {
    fontSize: 16,
    fontWeight: '700',
    color: '#4834d4',
  },
  reviewButton: {
    marginTop: 20,
    paddingVertical: 16,
    backgroundColor: '#f0f0f0',
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  reviewButtonText: {
    color: '#333333',
    fontSize: 16,
    fontWeight: '600',
  },
  solutionButton: {
    marginTop: 12,
    paddingVertical: 16,
    backgroundColor: '#2ed573',
    borderRadius: 12,
    alignItems: 'center',
  },
  solutionButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  solutionsContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  solutionsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    backgroundColor: '#ffffff',
  },
  backButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
  },
  solutionsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#333333',
    marginLeft: 16,
  },
  solutionsScroll: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  solutionCard: {
    backgroundColor: '#ffffff',
    marginHorizontal: 16,
    marginVertical: 8,
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  solutionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  solutionQuestionNumber: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333333',
  },
  solutionStatus: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  solutionCorrect: {
    backgroundColor: '#d4edda',
  },
  solutionIncorrect: {
    backgroundColor: '#f8d7da',
  },
  solutionStatusText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333333',
  },
  solutionQuestion: {
    fontSize: 16,
    color: '#333333',
    lineHeight: 24,
    marginBottom: 16,
  },
  solutionAnswers: {
    backgroundColor: '#f8f9fa',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  solutionAnswerText: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 4,
  },
  userAnswer: {
    fontWeight: '600',
    color: '#ff6b6b',
  },
  correctAnswer: {
    fontWeight: '600',
    color: '#2ed573',
  },
  solutionContent: {
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    paddingTop: 16,
  },
  solutionLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333333',
    marginBottom: 8,
  },
  solutionText: {
    fontSize: 14,
    color: '#444444',
    lineHeight: 22,
    marginBottom: 16,
  },
  finalAnswerLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333333',
    marginBottom: 8,
  },
  finalAnswerText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2ed573',
    backgroundColor: '#f0f8f0',
    padding: 12,
    borderRadius: 8,
  },
  analysisButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: '#4834d4',
    borderRadius: 12,
  },
  analysisButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#e0e0e0',
  },
  dividerText: {
    marginHorizontal: 16,
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
  },
  questionCountContainer: {
    marginBottom: 24,
  },
  questionCountLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 12,
  },
  questionCountButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  questionCountButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#f0f0f0',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  questionCountButtonActive: {
    backgroundColor: '#4834d4',
    borderColor: '#4834d4',
  },
  questionCountButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333333',
  },
  questionCountButtonTextActive: {
    color: '#ffffff',
  },
  subjectSection: {
    marginBottom: 24,
  },
  subjectHeader: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333333',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: '#4834d4',
  },
  topicsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  topicButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#f8f9fa',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    marginBottom: 8,
  },
  topicButtonSelected: {
    backgroundColor: '#4834d4',
    borderColor: '#4834d4',
  },
  topicButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333333',
  },
  topicButtonTextSelected: {
    color: '#ffffff',
    fontWeight: '600',
  },
  generateButton: {
    borderRadius: 15,
    overflow: 'hidden',
    marginTop: 24,
    marginBottom: 16,
  },
  generateButtonDisabled: {
    opacity: 0.7,
  },
  generatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  selectedSummary: {
    backgroundColor: '#e8f4fd',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#00d2ff',
  },
  selectedSummaryTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0066cc',
    textAlign: 'center',
  },
});